name: app_immobilier_mobile
description: "Application immobilière moderne"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  appwrite: ^12.0.4
  image_picker: ^1.2.1

  # ------------------- Remplacé Google Maps -------------------
  flutter_map: ^8.2.2   # Version à jour
  latlong2: ^0.9.0
  geolocator: ^10.1.1
  # ------------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  win32: ^5.15.0
  flutter_web_auth_2: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
